spring.application.name=VideoConsultatntAppDemo
server.port=8086
spring.profiles.active=dev


#account-sid=${TWILIO_SID}
#api-key=${TWILIO_API_KEY}
#api-secret=${TWILIO_SECRET}
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/video_consultantDB
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect