spring.application.name=VideoConsultatntAppDemo
server.port=8086
spring.profiles.active=devv

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/video_consultantDB
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect